Repository xiachufang/GT, pull requests merged in 2018-07, with the labels that each got.

#4 fix the frozen `c_time`
  storage.py
Labels: bug

#5 重构使用Slack-machine
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  app.py
  bot.py
  commands/create_db_and_tables.py
  config.py
  gt/__init__.py
  gt/config/__init__.py
  gt/config/database.py
  gt/plugins/__init__.py
  gt/plugins/chickens.py
  gt/store/__init__.py
  gt/store/storage.py
  gt/utils/__init__.py
  gt/utils/helpers.py
  run
  templates/install.html
  templates/thanks.html
  utils.py
Labels: 重构

#7 排行榜显示 pretty table
  .gitignore
  Pipfile
  Pipfile.lock
  gt/plugins/chickens.py
Labels: enhancement
